services:
  node:
    image: node:20.18
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev

  db:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=dvdrental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      default:
        aliases:
          - dvdrental-db
volumes:
  db-data:
